import { useEffect } from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion';
import ScrambleIn from './ScrambleIn';

const EASE_OUT = [0.215, 0.61, 0.355, 1.0] as const;
const FOLLOW = { stiffness: 55, damping: 18, mass: 0.7 };

interface HeroProps {
  entranceComplete: boolean;
}

/**
 * The opening statement. Each line sits at its own depth and drifts against
 * the pointer, so moving the mouse parallaxes the sentence apart — the
 * watermark trails furthest, the headline leads.
 */
export default function Hero({ entranceComplete }: HeroProps) {
  // -1..1 across the viewport, smoothed so the type glides rather than snaps.
  const px = useMotionValue(0);
  const py = useMotionValue(0);
  const sx = useSpring(px, FOLLOW);
  const sy = useSpring(py, FOLLOW);

  useEffect(() => {
    const onMove = (event: MouseEvent) => {
      px.set((event.clientX / window.innerWidth) * 2 - 1);
      py.set((event.clientY / window.innerHeight) * 2 - 1);
    };
    window.addEventListener('mousemove', onMove, { passive: true });
    return () => window.removeEventListener('mousemove', onMove);
  }, [px, py]);

  // Each layer travels a different distance against the pointer; the larger
  // the travel, the nearer it reads. Written out rather than generated by a
  // helper, so every hook call is plainly at the top level of the component.
  const watermarkX = useTransform(sx, [-1, 1], [14, -14]);
  const watermarkY = useTransform(sy, [-1, 1], [6, -6]);
  const leadX = useTransform(sx, [-1, 1], [30, -30]);
  const leadY = useTransform(sy, [-1, 1], [13, -13]);
  const counterX = useTransform(sx, [-1, 1], [20, -20]);
  const counterY = useTransform(sy, [-1, 1], [9, -9]);
  const bodyX = useTransform(sx, [-1, 1], [12, -12]);
  const bodyY = useTransform(sy, [-1, 1], [5, -5]);

  return (
    <section className="relative h-screen h-[100dvh] w-full overflow-hidden">
      <div
        className="pointer-events-none absolute inset-0"
        style={{
          backgroundImage: 'radial-gradient(#16151A 1px, transparent 1px)',
          backgroundSize: '24px 24px',
          opacity: 0.07,
        }}
      />

      <motion.div
        className="pointer-events-none absolute inset-0 flex items-center justify-center"
        style={{ x: watermarkX, y: watermarkY }}
        initial={{ opacity: 0 }}
        animate={{ opacity: entranceComplete ? 0.22 : 0 }}
        transition={{ duration: 1.8, ease: EASE_OUT }}
      >
        <span
          className="select-none whitespace-nowrap uppercase leading-none"
          style={{
            fontFamily: '"Anton SC", sans-serif',
            fontSize: 'clamp(120px, 30vw, 521px)',
            letterSpacing: '-4px',
            background: 'radial-gradient(circle, rgba(142,127,148,0) 0%, #8E7F94 70%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
          }}
        >
          Identity
        </span>
      </motion.div>

      <motion.div
        className="relative z-10 flex h-full flex-col px-4 pb-8 pt-20 sm:px-6 sm:pb-12 sm:pt-24 md:px-8"
        initial={{ opacity: 0, y: 18 }}
        animate={entranceComplete ? { opacity: 1, y: 0 } : { opacity: 0, y: 18 }}
        transition={{ duration: 1.6, ease: EASE_OUT }}
      >
        <div className="flex-1" />

        <div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between">
          <div className="flex flex-col gap-4">
            <motion.h1
              className="text-[clamp(40px,10vw,100px)] font-light leading-[0.95] tracking-[-0.03em] text-ink"
              style={{ x: leadX, y: leadY }}
            >
              <ScrambleIn text="Brand" delay={200} triggered={entranceComplete} />
              <br />
              <ScrambleIn text="And Build" delay={500} triggered={entranceComplete} />
            </motion.h1>

            <motion.p
              className="max-w-sm text-[13px] leading-relaxed text-ink/60 sm:text-[15px]"
              style={{ x: bodyX, y: bodyY }}
              initial={{ opacity: 0, y: 25 }}
              animate={entranceComplete ? { opacity: 1, y: 0 } : { opacity: 0, y: 25 }}
              transition={{ duration: 1.4, ease: EASE_OUT, delay: 0.35 }}
            >
              A studio for businesses that have outgrown the template they started on. Pick the
              trade below and see the page we would build you.
            </motion.p>
          </div>

          <motion.h1
            className="text-left text-[clamp(40px,10vw,100px)] font-light leading-[0.95] tracking-[-0.03em] text-ink md:text-right"
            style={{ x: counterX, y: counterY }}
          >
            <ScrambleIn text="One" delay={700} triggered={entranceComplete} />
            <br />
            <ScrambleIn text="Studio" delay={1000} triggered={entranceComplete} />
          </motion.h1>
        </div>
      </motion.div>
    </section>
  );
}
